services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: enriquecimiento_datos_negocio
      MYSQL_USER: user
      MYSQL_PASSWORD: 1573
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
